default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yourbook_development

test:
  <<: *default
  database: yourbook_test

production:
  <<: *default
  database: yourbook_production
  username: yourbook
  password: <%= ENV['SECRET_KEY_BASE'] %>

